titled: "Abdoulaye OUATTARA"
logo: "photo.jpg"   # Image de profil (mettre dans le dossier racine ou /assets/)
ddescription: >
  Junior Data Engineer | Expert Data Manager | Data Analyst  
  PassionnÃ© par la donnÃ©e, son traitement et sa valorisation pour la prise de dÃ©cision.

theme: jekyll-theme-minimal
lang: fr

# âš™ï¸ Options
show_downloads: false   # Pas nÃ©cessaire si ce nâ€™est pas une librairie
google_analytics: UA-XXXXXXXXX-X   # (optionnel : ajoute ton ID Google Analytics)
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

# ğŸŒ RÃ©seaux sociaux (affichÃ©s dans le footer si activÃ© par le thÃ¨me)
author:
  name: Abdoulaye  OUATTARA
  email: ton.email@mail.com
  linkedin: https://www.linkedin.com/in/abouattara/
  github: https://github.com/abdouattara
  twitter: https://twitter.com/tonpseudo   # facultatif

# ğŸ”— Liens rapides (apparaissent sous forme de navigation)
navigation:
  - name: "Accueil"
    link: /
  - name: "Projets"
    link: /projets
  - name: "Ã€ propos"
    link: /about
  - name: "Contact"
    link: /contact

# ğŸ“‘ SEO / mÃ©tadonnÃ©es
seo:
  name: "Abdoulaye OUATTARA"
  type: "Person"
  description: "Portfolio de Abdoulaye OUATTARA â€“ Junior Data Engineer, Expert Data Manager et Data Analyst."
  twitter_card: "summary"
